;;; casual-symbol-overlay-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-symbol-overlay.el

 (autoload 'casual-symbol-overlay-tmenu "casual-symbol-overlay" nil t)


;;; Generated autoloads from casual-symbol-overlay-settings.el

(register-definition-prefixes "casual-symbol-overlay-settings" '("casual-symbol-overlay-"))


;;; Generated autoloads from casual-symbol-overlay-utils.el

(register-definition-prefixes "casual-symbol-overlay-utils" '("casual-symbol-overlay-unicode-"))


;;; Generated autoloads from casual-symbol-overlay-version.el

(register-definition-prefixes "casual-symbol-overlay-version" '("casual-symbol-overlay-version"))

;;; End of scraped data

(provide 'casual-symbol-overlay-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-symbol-overlay-autoloads.el ends here
