;;; casual-ibuffer-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-ibuffer.el

 (autoload 'casual-ibuffer-tmenu "casual-ibuffer" nil t)


;;; Generated autoloads from casual-ibuffer-filter.el

(register-definition-prefixes "casual-ibuffer-filter" '("casual-ibuffer-"))


;;; Generated autoloads from casual-ibuffer-settings.el

(register-definition-prefixes "casual-ibuffer-settings" '("casual-ibuffer-"))


;;; Generated autoloads from casual-ibuffer-utils.el

(register-definition-prefixes "casual-ibuffer-utils" '("casual-ibuffer-"))


;;; Generated autoloads from casual-ibuffer-version.el

(register-definition-prefixes "casual-ibuffer-version" '("casual-ibuffer-version"))

;;; End of scraped data

(provide 'casual-ibuffer-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-ibuffer-autoloads.el ends here
