;;; consult-ag-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from consult-ag.el

(autoload 'consult-ag "consult-ag" "\
Consult ag for query in TARGET file(s) with INITIAL input.

(fn &optional TARGET INITIAL)" t)
(register-definition-prefixes "consult-ag" '("consult-ag--"))

;;; End of scraped data

(provide 'consult-ag-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; consult-ag-autoloads.el ends here
