;;; casual-editkit-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from casual-editkit.el

 (autoload 'casual-editkit-main-tmenu "casual-editkit" nil t)


;;; Generated autoloads from casual-editkit-constants.el

(register-definition-prefixes "casual-editkit-constants" '("casual-editkit-"))


;;; Generated autoloads from casual-editkit-settings.el

(register-definition-prefixes "casual-editkit-settings" '("casual-editkit-about"))


;;; Generated autoloads from casual-editkit-utils.el

(register-definition-prefixes "casual-editkit-utils" '("casual-editkit-"))


;;; Generated autoloads from casual-editkit-version.el

(register-definition-prefixes "casual-editkit-version" '("casual-editkit-version"))

;;; End of scraped data

(provide 'casual-editkit-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; casual-editkit-autoloads.el ends here
